### PR TITLE
feat(i18n): update zh-CN texts

### PR DESCRIPTION
**Pull request by breakeryu**
checked english version, and updata serial-monitor and libraries doc.

### CODE REVIEW

**Comment by urish** [comment]
Thank you so much! I hope to review it tomorrow and if all is fine, merge :)

**Comment by breakeryu** [comment]
ok，urish. By the way，can you add a Chinese language switch button? The website only has English and PT switch button now.

**Comment by urish** [comment]
Thanks! 

Yes, I enabled it now. I also updated all of the documents that haven't been translated yet to the latest version (so if you are viewing the Chinese docs, you won't get outdated information).

**Comment by urish** [comment]
Also, I noticed there are two shortcuts missing in the "General shortcuts" section of the "Editor Keyboard Shortcuts" guide:

```md
| Jump to next error in file      | F8              | F8      |
| Jump to previous error in file  | Shift + F8      | ⇧ F8    |
```

**Comment by breakeryu** [comment]
ok，thankyou for your help，urish。Have a good day~

**Pull request merged**
