### PR TITLE
Adding Arduino Nano simple example

### PR DESCRIPTION
**Pull request by DrCrowller**
Proposing a simple circuit with commented code as a basic example of an Arduino Nano controlling a servo with two colourblind-friendly coloured buttons.

### CODE REVIEW

**Comment by urish** [comment]
Thanks, the example looks good, but can you please place the wires in a way that they don't go over the parts?

image

**Comment by DrCrowller** [comment]
Sure ! It's fixed now.
The connections are overlapping with other pins, but that's the best I could manage to do.

**Comment by urish** [comment]
How about changing diagram.json as follows?

```json
{
  "version": 1,
  "author": "Anonymous maker",
  "editor": "wokwi",
  "parts": [
    { "type": "wokwi-arduino-nano", "id": "nano", "top": 0, "left": 0, "attrs": {} },
    {
      "type": "wokwi-pushbutton",
      "id": "btn1",
      "top": 157.53,
      "left": 78.09,
      "attrs": { "color": "yellow", "label": "ROTATE RIGHT" }
    },
    {
      "type": "wokwi-servo",
      "id": "servo1",
      "top": -175.96,
      "left": 104.81,
      "rotate": 270,
      "attrs": { "hornColor": "black" }
    },
    {
      "type": "wokwi-pushbutton",
      "id": "btn2",
      "top": 83.67,
      "left": 76.98,
      "attrs": { "color": "blue", "label": "ROTATE LEFT" }
    }
  ],
  "connections": [
    [ "btn1:2.r", "nano:GND.1", "black", [ "h0" ] ],
    [ "btn2:2.r", "nano:GND.1", "black", [ "h0" ] ],
    [ "btn2:1.l", "nano:A1", "blue", [ "h0" ] ],
    [ "btn1:1.l", "nano:A2", "green", [ "h0" ] ],
    [ "nano:5V", "servo1:V+", "red", [ "v14.4", "h66.7" ] ],
    [ "servo1:GND", "nano:GND.2", "black", [ "v18.86", "h-52.51" ] ],
    [ "servo1:PWM", "nano:2", "green", [ "v9.26", "h-81.11" ] ]
  ]
}
```

**Comment by DrCrowller** [comment]
Sure !
I didn't know you could specify coordinates for the connections' bendings;
I also modified the colours in order to match with the buttons and be colourblind-friendly.

**Comment by urish** [comment]
Thanks!

Did you make originally make the diagram connections by editing diagram.json or by clicking with the mouse?
When using the mouse, there's also a [grid mode](https://docs.wokwi.com/guides/diagram-editor#grid-snapping), which makes it easy to organize the wires with consistent spacing

**Comment by DrCrowller** [comment]
I used the GUI to make the diagrams, but I'm quite new to this interface (I'm more used to physical drawings).
Thank you for the tip and the corrections, I'll keep them in mind for my next examples and productions.

**Comment by urish** [comment]
Any ideas how to make it more obvious that you can bend the wires with the GUI?

**Comment by DrCrowller** [comment]
Maybe by changing the colour of the grid's dots, or highlighting them, when you hover them with a wire, like the pins ?
Making a separate button for toggling the grid might also help to emphasize on it.

**Pull request merged**
